ignore:
  - "spatialyze/video_processor/modules/**/*"
  - "spatialyze/video_processor/stages/detection_estimation/**/*"
  - "spatialyze/video_processor/stream/exit_frame_sampler.py"
  - "**/__init__.py"
