ignore:
  - "spatialyze/video_processor/modules"
  - "spatialyze/video_processor/stages/detection_estimation/*"
  - "spatialyze/video_processor/stages/segment_trajectory/*"
  - "spatialyze/video_processor/stages/strongsort_with_skip.py"
  - "spatialyze/video_processor/utils/format_trajectory.py",
  - "spatialyze/video_processor/stages/tracking/deepsort.py",
  - "spatialyze/video_processor/stages/tracking_2d/deepsort.py",
  - "spatialyze/video_processor/stream/deepsort.py",
  - "spatialyze/video_processor/stages/detection_3d/ground_truth.py",
  - "**/__init__.py"