services:
  dev:
    build: .
    container_name: spatialyze
    tty: true
    environment:
      - TERM=xterm-256color
    volumes:
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: "host"
