title: Spatialyze
description: "A Geospatial Video Analytic System with Spatial-Aware Optimizations"
theme: just-the-docs

url: https://apperception-db.github.io/spatialyze

aux_links:
  GitHub: https://github.com/apperception-db/spatialyze

nav_external_links:
  - title: API
    url: https://apperception-db.github.io/spatialyze/api
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false