name: Generate Videos
on:
  push:
    branches-ignore:
      - 'main'
      - 'dev'

jobs:
  generate-videos:
    name: Generate Videos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT || github.token }}
          submodules: recursive

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: spatialyze
          create-args: >-
            -c conda-forge
            python=3.10
            poetry=1.5.1
          init-shell: none
          cache-downloads: false

      - name: Check Python Versions
        shell: micromamba-shell {0}
        run: |
          python --version
          python3 --version
          which python
          which python3
          which pip
          which pip3
          which poetry

      - name: Install Dependencies
        shell: micromamba-shell {0}
        run: poetry install --no-interaction --without dev --with test
      
      - name: Check Installed Packages
        shell: micromamba-shell {0}
        run: pip list
      
      - name: Ingest Road
        shell: micromamba-shell {0}
        run: python ./scripts/ingest_road.py
        env:
          AP_PORT: 25432
          AP_HOST: localhost
      
      - name: Generate Video Examples
        shell: micromamba-shell {0}
        run: python evaluation/examples/inference_pipeline.py
        env:
          AP_PORT: 25432
          AP_HOST: localhost

      - name: Commit generated examples
        run: ./scripts/commit-and-push-if-latest.sh "[CI] generate video examples"